M48
; DRILL file {KiCad 8.0.7} date 2025-01-03T20:06:23-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-03T20:06:23-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,Plated,4,6,Blind
FMAT,2
INCH
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.0040
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T2C0.0060
%
G90
G05
T1
X3.3879Y-2.5784
T2
X3.2795Y-2.7512
M30
